name: Security Check

on:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Change directory to repository root
      run: cd $GITHUB_WORKSPACE
      
    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2
      
    - name: Run Composer audit
      run: composer audit
